# -*- coding: utf-8 -*-
"""
自主玩家智能体的严格、版本化且无副作用的公共契约。

作者: Project contributors
创建日期: 2026-07-29
修改日期: 2026-07-31
"""

from werewolf_agent.player_agents.contracts.disclosure import DisclosureGrant
from werewolf_agent.player_agents.contracts.dispatch import (
    ActiveTurnDispatchFence,
    DispatchAttempt,
    DispatchOperationKind,
    DispatchRecoveryPolicy,
    DispatchResultDisposition,
    DispatchResultOutcome,
    DispatchResultRecord,
    DispatchStatus,
)
from werewolf_agent.player_agents.contracts.errors import (
    ProposalFailure,
    ValidationErrorCode,
)
from werewolf_agent.player_agents.contracts.proposals import SpeechProposalEnvelope
from werewolf_agent.player_agents.contracts.records import (
    PublicSpeechRecord,
    RecordOrigin,
    RenderedUtterance,
)
from werewolf_agent.player_agents.contracts.revisions import (
    ReadReference,
    RevisionContext,
)
from werewolf_agent.player_agents.contracts.scheduling import (
    ManagedAgentTurn,
    SerialPublicSchedule,
    SerialPublicScheduleStatus,
    SerialPublicSlot,
    TerminalDisposition,
    TurnAdmission,
)
from werewolf_agent.player_agents.contracts.schema_catalog import (
    SCHEMA_VERSION,
    speech_proposal_schema,
    speech_proposal_schema_hash,
)
from werewolf_agent.player_agents.contracts.speech import (
    AddressStyle,
    Alignment,
    AlignmentRead,
    ClaimMode,
    ComparisonDimension,
    ConditionalCommitment,
    ConfidenceBucket,
    ConsequenceKind,
    EvidenceRelation,
    LengthClass,
    Modality,
    PlayerComparison,
    PrivateFactKind,
    PrivateResultDisclosure,
    PublicEvidenceCitation,
    QuestionMove,
    QuestionTopic,
    RequestedField,
    ResponseKind,
    ResponseMove,
    RetractionMove,
    RoleClaim,
    SpeechMove,
    SpeechObjective,
    SpeechProposalBody,
    Strength,
    Tone,
    UncertaintyDimension,
    UncertaintyStatement,
    VoteCommitment,
    VotePosition,
)
from werewolf_agent.player_agents.contracts.transactions import (
    CommitResult,
    CommitTurnRequest,
    CriticalAuditRecord,
    EventCandidate,
    ProjectionOutboxRecord,
)
from werewolf_agent.player_agents.contracts.turns import (
    AgentTurn,
    AgentTurnStatus,
    ConflictClass,
    LegalActionWindow,
    TurnBudget,
    transition_turn,
)

__all__ = [
    "SCHEMA_VERSION",
    "ActiveTurnDispatchFence",
    "AddressStyle",
    "AgentTurn",
    "AgentTurnStatus",
    "Alignment",
    "AlignmentRead",
    "ClaimMode",
    "CommitResult",
    "CommitTurnRequest",
    "ComparisonDimension",
    "ConditionalCommitment",
    "ConfidenceBucket",
    "ConflictClass",
    "ConsequenceKind",
    "CriticalAuditRecord",
    "DisclosureGrant",
    "DispatchAttempt",
    "DispatchOperationKind",
    "DispatchRecoveryPolicy",
    "DispatchResultDisposition",
    "DispatchResultOutcome",
    "DispatchResultRecord",
    "DispatchStatus",
    "EventCandidate",
    "EvidenceRelation",
    "LegalActionWindow",
    "LengthClass",
    "ManagedAgentTurn",
    "Modality",
    "PlayerComparison",
    "PrivateFactKind",
    "PrivateResultDisclosure",
    "ProjectionOutboxRecord",
    "ProposalFailure",
    "PublicEvidenceCitation",
    "PublicSpeechRecord",
    "QuestionMove",
    "QuestionTopic",
    "ReadReference",
    "RecordOrigin",
    "RenderedUtterance",
    "RequestedField",
    "ResponseKind",
    "ResponseMove",
    "RetractionMove",
    "RevisionContext",
    "RoleClaim",
    "SerialPublicSchedule",
    "SerialPublicScheduleStatus",
    "SerialPublicSlot",
    "SpeechMove",
    "SpeechObjective",
    "SpeechProposalBody",
    "SpeechProposalEnvelope",
    "Strength",
    "TerminalDisposition",
    "Tone",
    "TurnAdmission",
    "TurnBudget",
    "UncertaintyDimension",
    "UncertaintyStatement",
    "ValidationErrorCode",
    "VoteCommitment",
    "VotePosition",
    "speech_proposal_schema",
    "speech_proposal_schema_hash",
    "transition_turn",
]
