# -*- coding: utf-8 -*-
"""
功能描述：游戏持久化仓库接口——games/events/deaths/model_usage/evaluations/config_snapshots（设计文档 §13）。
作者：Mike
创建日期：2025-01-15
修改日期：2026-07-05
使用示例：内部模块，无对外接口
"""

from __future__ import annotations

from typing import Any, Protocol

from werewolf_agent.core.models import Death, GameEvent, GameState


class GameRepository(Protocol):
    """Storage contract for all game data.

    Implementations must support:
    - Save/load game state (round-trip exact)
    - Append events with ordering guarantees
    - Store deaths, model usage, evaluation results, config snapshots
    - List and delete games
    """

    def save_game(self, state: GameState) -> None: ...
    def load_game(self, game_id: str) -> GameState | None: ...
    def append_events(self, game_id: str, events: list[GameEvent]) -> None: ...
    def load_events(self, game_id: str) -> list[GameEvent]: ...
    def save_deaths(self, game_id: str, deaths: list[Death]) -> None: ...
    def load_deaths(self, game_id: str) -> list[Death]: ...
    def save_model_usage(self, game_id: str, record: dict[str, Any]) -> None: ...
    def load_model_usage(self, game_id: str) -> list[dict[str, Any]]: ...
    def save_evaluation(self, game_id: str, result: dict[str, Any]) -> None: ...
    def load_evaluation(self, game_id: str) -> dict[str, Any] | None: ...
    def save_config_snapshot(self, game_id: str, config: dict[str, Any]) -> None: ...
    def load_config_snapshot(self, game_id: str) -> dict[str, Any] | None: ...
    def save_rag_entries(self, entries: list[dict[str, Any]]) -> None: ...
    def load_rag_entries(self) -> list[dict[str, Any]]: ...
    def delete_rag_entry(self, entry_id: str) -> None: ...
    def save_custom_config(self, record: dict[str, Any]) -> None: ...
    def load_custom_config(self, config_id: str) -> dict[str, Any] | None: ...
    def list_custom_configs(self, config_type: str | None = None) -> list[dict[str, Any]]: ...
    def list_games(self) -> list[GameState]: ...
    def delete_game(self, game_id: str) -> None: ...
    # -- Memory snapshots (S4 post-review-v2: signatures match PostgresGameRepository) --
    def save_memory_snapshot(self, snapshot_id: str, data: dict[str, Any]) -> None: ...
    def load_memory_snapshot(self, snapshot_id: str) -> dict[str, Any] | None: ...
    def list_memory_snapshots(self) -> list[dict[str, Any]]: ...
    # -- Reflections (S4 post-review-v2: signatures match PostgresGameRepository) ------
    def save_reflection(self, entry: dict[str, Any]) -> None: ...
    def load_reflections_by_game(self, game_id: str) -> list[dict[str, Any]]: ...
    def load_reflections_by_player(self, player_id: str) -> list[dict[str, Any]]: ...
    def load_all_reflections(self) -> list[dict[str, Any]]: ...
    def delete_reflection(self, entry_id: str) -> None: ...
