"""Repository interface for game persistence.

Design doc §13: V1 uses SQLite or local files as development substitutes.
Interface boundary follows production design: games, events, deaths,
model usage, evaluation results, and config snapshots.
"""

from __future__ import annotations

from typing import Any, Protocol

from werewolf_agent.core.models import Death, GameEvent, GameState


class GameRepository(Protocol):
    """Storage contract for all game data.

    Implementations must support:
    - Save/load game state (round-trip exact)
    - Append events with ordering guarantees
    - Store deaths, model usage, evaluation results, config snapshots
    - List and delete games
    """

    def save_game(self, state: GameState) -> None: ...
    def load_game(self, game_id: str) -> GameState | None: ...
    def append_events(self, game_id: str, events: list[GameEvent]) -> None: ...
    def load_events(self, game_id: str) -> list[GameEvent]: ...
    def save_deaths(self, game_id: str, deaths: list[Death]) -> None: ...
    def load_deaths(self, game_id: str) -> list[Death]: ...
    def save_model_usage(self, game_id: str, record: dict[str, Any]) -> None: ...
    def load_model_usage(self, game_id: str) -> list[dict[str, Any]]: ...
    def save_evaluation(self, game_id: str, result: dict[str, Any]) -> None: ...
    def load_evaluation(self, game_id: str) -> dict[str, Any] | None: ...
    def save_config_snapshot(self, game_id: str, config: dict[str, Any]) -> None: ...
    def load_config_snapshot(self, game_id: str) -> dict[str, Any] | None: ...
    def save_custom_config(self, record: dict[str, Any]) -> None: ...
    def load_custom_config(self, config_id: str) -> dict[str, Any] | None: ...
    def list_custom_configs(self, config_type: str | None = None) -> list[dict[str, Any]]: ...
    def list_games(self) -> list[GameState]: ...
    def delete_game(self, game_id: str) -> None: ...
